### ISSUE TITLE
Start mapping key concepts/frameworks/ideological inspirations (as well as orgs)

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#165]

**Comment by catherinet1** [comment]
We'll probably do this for now by using linking function in Obsidian more as we are filling in research profiles

**Comment by catherinet1** [comment]
cf https://github.com/orgs/life-itself/discussions/949

**Comment by rufuspollock** [comment]
@catherinet1 should this remain open?

**Comment by catherinet1** [comment]
WONTFIX. This was more of a someday/maybe rather than specific issue for current focus and probably covered/superseded by wiki work currently.
