### ISSUE TITLE
Interview ecosystem network or node "experts" to identify tribes/centres of the field

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#199]
A suggested possible action from visualisation meeting https://github.com/life-itself/ecosystem/issues/180

- Identify a few nodal/network "experts" and record conversations where people draw out their own map of the space/identify communities?
  - e.g. Richard Bartlett, Elizabeth Debold/Thomas Steininger (closer to Integral), someone from Plum Village (Zen Buddhism)

i.e. people who are well connected in certain communities within the broader ecosystem

**Comment by rufuspollock** [comment]
DUPLICATE / SOMEDAY. Moved to forum ideas section https://forum.secondrenaissance.net/t/mapping-parties-where-people-comment-on-ecosystem-map-and-or-develop-their-own-maps/32
