### ISSUE TITLE
Volunteer Database Research - Anastasia

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#235]
## Acceptance

- [ ] 5 basic organisation profiles completed (basic profile = contains frontmatter, image, and description)

### Technical setup

- [ ] Create GitHub account
- [ ] Download Obsidian
- [ ] Download GitHub desktop
- [ ] Set up GitHub desktop with your GitHub account
- [ ] Get the ecosystem repo to be editable on your local machine in Obsidian
  - [ ] Click green 'Code' button in ecosystem repo 
  - [ ] Click 'Open with Github Desktop'
  - [ ] Click 'fetch origin'
- [ ] Set up Obsidian according to these guidelines: https://github.com/orgs/life-itself/discussions/927

#### Main Task
- [ ] For 5 organisations from this list: https://docs.google.com/spreadsheets/d/1VbMvdy_pPzdREsAsXxONZWbPWS0rLxsy-NWJCg1cYDw/edit#gid=0
  - [ ] Create basic profiles, i.e. fill in frontmatter fields, add description, and add an image (screenshot of homepage) N.B. Add the image in the main body of the profile _as well as_ in the image frontmatter field. 
- [ ] Log any questions that come up below

#### Secondary Task

For each organisation:
  - [ ] Give a rough numerical estimate of how close it is to the "centre" of the Second Renaissance ecosystem (cf outline of key characteristics: https://ecosystem.lifeitself.org/)
  - [ ] Write "quick and dirty" rough note why

### How to Create a Profile

- Open Github Desktop
- Select ecosystem as current repository
- Click 'fetch origin' to sync your local clone of the repo with the remote repo
- Create a new branch for the edits you are about to make
- Open ecosystem/content in Obsidian
- Create new note in Obsidian **in the tbd folder**
- Insert template named "profile"
- Fill in profile, in accordance with "profile-documentation" guidelines
- In Github Desktop: commit your changes to the branch you created
- In Github Desktop, click 'Publish branch'
- In Github online, create pull request and request review

Video walkthrough: https://drive.google.com/file/d/1nVILlZN5MWUkcmPBQFv9qOV7pKZBRtdn/view?usp=sharing

**Comment by catherinet1** [comment]
2024-03-01: 
- Met Anastasia and introduced task. Video walkthrough of how to create a new profile linked above.
- Anastasia aiming to complete next week.

**Comment by rufuspollock** [comment]
FIXED / WONTFIX. Migrated content and instructions to https://forum.secondrenaissance.net/t/how-to-contribute-to-the-organization-directory-database/31

I think in end Anastasia didn't help out.
