### ISSUE TITLE
Troubleshooting cloning repo

### ISSUE THREAD

**Issue by oolu4236** [life-itself/second-renaissance#277]
I'm having some problems cloning the ecosystem repository. Checking if there are any alternatives to cloning the full repository, and a detailed step-by-step guide for setting up obsidian and GitHub desktop and linking them to the ecosystem.

![Screen Shot 2024-04-11 at 4 05 58 AM](https://github.com/life-itself/secondrenaissance/assets/93337521/0a3b36f2-30da-46e8-849e-6f08d4942ad5)

**Comment by rufuspollock** [comment]
I would just retry.

**Comment by oolu4236** [comment]
Yeap. I re-tried. Could be my PC or something. I'd keep trying

**Comment by rufuspollock** [comment]
@oolu4236 you may also want to make sure you have git-lfs enabled.
