### ISSUE TITLE
Update and tidy ecosystem mapping work, especially landing pages for v0.2 (april 2024)

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#283]
```[tasklist]
### Acceptance
- [ ] https://github.com/life-itself/secondrenaissance/issues/276
- [ ] https://github.com/life-itself/ecosystem/issues/251
- [ ] https://github.com/life-itself/ecosystem/issues/250
- [ ] https://github.com/life-itself/ecosystem/issues/249
- [x] [MAYBE] Cohere ecosystem mapping landing page 🚧 (see below) **✅2024-06-30 ❌ wontfix and now have superseded by #315**
```

### Cohere "draft" mapping report/landing page ❌

- [ ] Landing page live at `/ecosystem/cohere-2023`
- [ ] Contains Co-funded by EU logo
- [ ] Contains Cohere+ logo and names and logos of Cohere+ partners
- [ ] Link to Cohere+ project announce: https://lifeitself.org/blog/2023/08/30/cohere-erasmus-mapping-announce
- [ ] Share our inclusion criteria (?)
- [ ] Publish (tidied up) Cohere+ mapping "needs analysis"/job stories (?) https://docs.google.com/document/d/14ppodYcLkCZU3k9jlFzsIr9FSW1iAX0wQlJLInYQ1IY/edit

### Unscoped

**🚚2024-06-30: to #257**

- [ ] Synonym names essay extended: We compare previous approaches and draw out key insights and disagreements we may have
- [ ] Rosetta: Glossary of concepts and maps between them e.g. Effective vMeme = Worldview Family = Cultural Paradigm OR Metacrisis =? Polycrisis
- [ ] [Key thinkers/ideas - [Overlaps with 2R level 1]]
- [ ] BONUS ? Metacrisis definition piece

## Pitch & Intention

Pitch (Ecosystem section on 2R): https://github.com/life-itself/comms/blob/main/pitch/2413%20Ecosystem%20section%20on%202R.md

**🔑 Intention: demonstrate to people something *is* happening and allowing people to orient to the space i.e. either matching to landmarks in space or proximate to it.**

- Framing of "there is emerging ecosystem and here is the evidence"
- Allows people to orient within space e.g. synonyms, rosetta stone
- People proximate or outside 2nd R to orient e.g. to see how relates to things they already know
- Allow people who want to go deeper to do so (e.g. other people doing mapping etc)

Secondarily

- An overview of mapping work that has been done (rather than one specific effort v2021 as currently).
- Demonstrate the fact we have done significant research here (shows credibility to rest of work - equivalent of a literature review) - here's some of the work we've done, here's some of the work others have done etc

**Comment by rufuspollock** [comment]
FIXED. Complete back in April 2024. Moved bonus stuff where relevant to inbox.
