### ISSUE TITLE
Second Renaissance Online Introduction Course

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/second-renaissance#334]
Secondrenaissance.net is a new accessible resource for newcomers to the Second Renaissance space. A co-created discussion/presentation was recently piloted in-person at a Hub Residency in June 2024. Given the focus on the 2R movement and a recent backlog review, creating a 2R Zoom course to further engage newcomers is a prioritized next step. Why? To share and bring to life the essence of the Second Renaissance in an inspiring way so that attendees receive inspiring information, and co-sense-make with others providing an opportunity to be interactive and connect with people and leave the course with a sense of empowerment and personal and collective resonance of why it is important to be involved in creating this paradigm shift.

## Acceptance

- [x] Sign up target met - 20 people ✅ **25 sign ups** / 500euros ❌ 
- [x] Course hosted

### Marketing / Sharing

**Before 9th July**
- [x] Rufus/Sylvie review proposal and sign off
  - [x] Logistics sign off - dates / times etc  -31st July & 1st Aug 6-8pm CET
  - [x] Price agreed 10euros standard (3-50 euros sliding scale)
- [x] Listen / review recording of session run at the Hub on 28 June
- [x] Copy drafted for registration page and promotional copy 🚧 [document](https://docs.google.com/document/d/1YhpP3WIko4a9c6hMzTzpHEldFFSssAxOukvJp87mR-Y/edit)
- [x] Visual for course decided
- [x] Landing registration page set up - https://lu.ma/f941uctv
- [x] Payment page set up on lu.ma - do with Rufus as authorisation linked to his phone
- [x] Announcement made in Connection Call on 9th
- [x] Set up zoom link for lu.ma confirmation emails

**After 9th July**
- [x] Announcement on 2R substack
- [x] Design/create announcement images
- [x] Initial Announcements made on Socials and Discord _posted on whatsapp, discord, IG, twitter and event on LinkedIn._
- [ ] Schedule of posting / announcing made ❌ _not done as timeframe reduced_
- [ ] Posting done daily to promote
  - [ ] Bonus: short 1 min reel on it (can be reused)
- [x] Added to Second Renaissance website 
- [ ] Included in July Newsletter
- [x] Add to LI Events Calendar
- [x] [Mailout sent one week before the event ](https://secondrenaissance.substack.com/p/join-our-upcoming-second-renaissance?r=3kjpzv)
- [ ] Draft copy to share with others in our network to include in their newsletters
- [x] Plan content and requirements for each session _allocated to Rufus and Sylvie now_
- [ ] Design / check slides if required
- [ ] Invite people directly - personal messages / emails etc
- [x] Send reminder emails ahead of sessions (schedule on lu.ma) ✅ _scheduled to go out via lu.ma_
  - [x] 1 day
  - [x] 1 hours
  - [x] 15 mins
- [x] Host sessions (include time for feedback completion on last session)
- [x] Send a thank you email 🚧 _draft copy in doc ready to be added to lu.ma_
  - [x] Resend feedback link (in case) ✅ _included in copy_
- [x] Offer next steps ✅  _added CTA for next Connection Call_
- [ ] Pre-sign up for next Intro link for next course to share with friends - to decide when?
- [x] Conversations: Rufus, Sylvie, Curators Team, Advisors, attendees at Connection Call
- [x] Debrief meeting _scheduled 2024-08-07_
- [x] Next steps agreed

### Content and 

```[tasklist]
### Course content
- [ ] [Structure here](https://docs.google.com/document/d/1RLryGyZhgQzNviyWfOYeYD3l_Ip9pj3y5ziZkbqB-Lo/edit)
```

```[tasklist]
### Delivery
- [x] [Create feedback form](https://docs.google.com/forms/d/1vu2EnkTweaMahUQ6lex6vNUP1wCMuqO96vk3irlcvTs/edit)
- [ ] Next course created
- [ ] ...
```

## Notes

2024-07-31 2R Course Sync Meeting

Present: Lauren, Rufus, Sylvie
Intention: To ensure we are fully prepared and ready for the course tonight and all tasks have been done

Key Responsibilities in call of producer:

- welcome/admit attendees and emergency contact shared in reminder emails
- open breakout rooms - ensure people are paired with different people for each breakout room
- Any late arrivals, take to one side (in a seperate room) and provide an update of where we have got to and where we are now, so they can enter with confidence
- recap sent at the end of course and zoom link for recording sent
- See document above for more notes

**Comment by rufuspollock** [comment]
@laurenwigmore i think we could email the people on our course sign up list https://app.brevo.com/contact/list/id/33 (i also think we could subscribe them to the second renaissance newsletter if they aren't already)

**Comment by laurenwigmore** [comment]
> @laurenwigmore i think we could email the people on our course sign up list https://app.brevo.com/contact/list/id/33 (i also think we could subscribe them to the second renaissance newsletter if they aren't already)

I've sent the subscribers to the pilot course an email, and added the 14 that weren't subscribed to our Substack newsletter, with a note at the bottom of the course email about being added.

**Comment by laurenwigmore** [comment]
@rufuspollock @shiweiart just checking in with where you are at with the content and slides ahead of next week?
and a reminder for Rufus if you could review why the page isn't building for me please, so I can update the course page on the website.

**Comment by rufuspollock** [comment]
Site page is now building.

We will work on structure in next few days.
